### ISSUE TITLE
Problemas con www.powvideo.net

### ISSUE THREAD

**Issue by b4zz4** [koji3/Streaming-dl#1]
estuve probando me funciona perfecto con vidspot.net pero no con powvideo, por lo que veo el formulario es diferente

**Comment by ncortex** [comment]
Actualmente solo tiene soporte para AllMyVideos, VidSpot, Played.to y StreamCloud. Powvideo trabaja de otra forma y no es tan fácil obtener el link final del vídeo.

**Comment by b4zz4** [comment]
ahí logre obtenerlo, envie el formulario varias veces y con cookies y la URL esta mezclada en javascript 
https://github.com/b4zz4/Pirata-loro-pirata/blob/master/streaming-dl

**Comment by ncortex** [comment]
Okey, ya he descubierto como forma la url. Añadida la opción de descargar desde powvideo. Se agradece Feedback.
